head: 
   favicon: "http://www.52gmk.com/view/img/favicon.ico" #  the favicon
   high_res_favicon: "http://www.52gmk.com/view/img/favicon.ico" #  the favicon using high quality format
   apple_touch_icon: "http://www.52gmk.com/view/img/favicon.ico" # the iOS Home button icon
   keywords: "gamemaker gamemakerchina" #  the site keywords
header:
    m_header: true
    m_color: mdui-color-green-400
    m_background_url: "https://i.loli.net/2018/03/24/5ab63232e1e64.jpg"
    headroom: false
    m_icon_color: green
uiux:
   android_chrome_color: "#eeeeee" #  the color of the Chrome address bar
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: false
background: 
   purecolor: "#eeeeee" # the background color
img: 
   avatar: "" # your avatar
card: 
   card_shadow: 5 # card shadow (0-24), 0 is not displayed
   card_hoverable: true # When the hover to deepen the shadow
many_authors: true
sns_share: # SNS Share Switch
   twitter: false
   facebook: false
   googleplus: false
   weibo: false
   linkedin: false
   qq: false
   telegram: false
comment:
  used: "gitment" # disqus,livere,gitment,valine
  # disqus config
  disqus_shortname: "" # Your disqus 
  disqus_button: true # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: 'MTAyMC8yOTQ5Mi82MDYw'
  # gitment config
  owner: "Mysaku"
  repo: "jekyll-theme-mdui"
  client_id: "2945e26ca36ad881e9b5"
  client_secret: "816e328c91af9099932699cff0b18bc9a535213b"
  #valine config
  valine_notify: false #mail notifier
  valine_verify: false #validation code
  valine_app_id: ''
  valine_app_key: ''
  valine_placeholder: "ヾﾉ≧∀≦)o来啊，快活啊!"
passage:
  describe: true
prism:
  themes: prism-okaidia
  components: 
    - bash 
  plugins: 
mathjax: false
google_analytics: ""  # google analytics code
baidu_site_verification: ""  # baidu site verification code
google_site_verification: ""  # google search console verification code
baidu_auto_push: false  # if you used baidu auto push to commit links
lang: "zh-CN"  # lang
deploy: "" # if you used coding pages
custom_css: ".header-image {display: none;}" # Use the assets/css/customCss.css
custom_js: "" # Use the assets/js/customJS.js